-- ARC-4: schema "audit" — auditoria e rastreabilidade, não mais cópias das tabelas de negócio.
-- Contém apenas: log genérico de alterações (aud_changelog) e jornada do usuário por evento
-- (aud_userjourney). Substitui o modelo anterior de uma tabela de log por entidade.
-- Identificadores em minúsculo e SEM aspas (ver comentário em Postgres/Core/script-1.0.0.sql).

CREATE SCHEMA IF NOT EXISTS audit;

-- Log genérico de alteração (create/update/delete) de qualquer entidade de negócio do schema core.
CREATE TABLE audit.aud_changelog
(
    id              bigint       generated by default as identity constraint pk_changelog primary key,
    entityname      varchar(120) not null,
    entityid        varchar(120) not null,
    targetoperation char(1)      not null,
    snapshotjson    jsonb        null,
    operation       char(1)      not null,
    lastchangeat    timestamp    not null,
    lastchangeby    varchar(255) not null
);

CREATE INDEX idx_changelog_entity ON audit.aud_changelog (entityname, entityid);
CREATE INDEX idx_changelog_snapshotjson ON audit.aud_changelog USING gin (snapshotjson);

-- Jornada do usuário por evento (sign-in, transferência criada/negada, etc.), correlacionada por correlationid.
CREATE TABLE audit.aud_userjourney
(
    id            bigint       generated by default as identity constraint pk_userjourney primary key,
    correlationid varchar(64)  not null,
    iduser        uuid         null,
    eventtype     varchar(80)  not null,
    resource      varchar(255) null,
    payloadjson   jsonb        null,
    ip            varchar(64)  null,
    useragent     varchar(255) null,
    occurredat    timestamptz  not null default now()
);

CREATE INDEX idx_userjourney_iduser ON audit.aud_userjourney (iduser);
CREATE INDEX idx_userjourney_correlationid ON audit.aud_userjourney (correlationid);
CREATE INDEX idx_userjourney_payloadjson ON audit.aud_userjourney USING gin (payloadjson);
