-- ARC-4: schema "core" — equivalente ao antigo banco Trade_Prod (SQL Server), agora em PostgreSQL/Supabase.
-- Identificadores em minúsculo e SEM aspas: o Postgres dobra identificador sem aspas para minúsculo
-- independente do case usado no texto do SQL, e todo o SQL manual do projeto (Persistence/**/Queries/*.cs)
-- referencia tabela/coluna sem aspas — então o catálogo precisa estar em minúsculo para essas queries
-- resolverem. O EF Core (MainContext/AuditContext/BaseContext.LowercaseIdentifiers) também mapeia tudo
-- para minúsculo, então os dois lados batem.

CREATE SCHEMA IF NOT EXISTS core;

CREATE TABLE core.ath_users
(
    id                 uuid          not null default gen_random_uuid() constraint pk_user primary key,
    email              varchar(120)  not null,
    normalizedemail    varchar(120)  not null,
    securitystamp      varchar(120)  not null,
    isemailconfirmed   boolean       not null,
    passwordhash       varchar(258)  not null,
    isactive           boolean       not null,
    lockoutend         timestamptz   null,
    accessfailedcount  integer       not null default 0,
    lockoutenabled     boolean       not null default true,
    operation          char(1)       not null,
    lastchangeat       timestamp     not null,
    lastchangeby       varchar(255)  not null
);

CREATE TABLE core.dcm_types
(
    id   int          not null constraint pk_document primary key,
    name varchar(125) not null
);

CREATE TABLE core.ppl_type
(
    id   int          not null constraint pk_persontype primary key,
    name varchar(125) not null
);

CREATE TABLE core.ppl_people
(
    id                       uuid         not null constraint pk_person primary key references core.ath_users (id),
    firstname                varchar(125) not null,
    lastname                 varchar(125) not null,
    avatar                   varchar(800) null,
    birthdate                timestamp    not null,
    isactive                 boolean      not null,
    documentnumber           varchar(80)  not null,
    normalizeddocumentnumber varchar(80)  not null,
    documenttype             int          not null constraint fk_person_document references core.dcm_types (id),
    persontype               int          not null constraint fk_person_type references core.ppl_type (id),
    dateinclusion            timestamp    not null,
    operation                char(1)      not null,
    lastchangeat             timestamp    not null,
    lastchangeby             varchar(255) not null
);

CREATE TABLE core.wlt_wallets
(
    id           uuid         not null default gen_random_uuid() constraint pk_wallet primary key,
    iduser       uuid         not null constraint fk_wallet_user references core.ath_users (id),
    publickey    varchar(800) not null,
    hash         varchar(255) not null,
    isblocked    boolean      not null,
    isactive     boolean      not null,
    operation    char(1)      not null,
    lastchangeat timestamp    not null,
    lastchangeby varchar(255) not null
);

CREATE TABLE core.wlt_transactions
(
    id           uuid           not null default gen_random_uuid() constraint pk_wallettransaction primary key,
    idwalletfrom uuid           not null constraint fk_wallettransaction_walletfrom references core.wlt_wallets (id),
    idwalletto   uuid           not null constraint fk_wallettransaction_walletto references core.wlt_wallets (id),
    amount       numeric(18, 8) not null,
    idblock      uuid           null,
    iscredit     boolean        not null default false,
    isblocked    boolean        not null,
    operation    char(1)        not null,
    lastchangeat timestamp      not null,
    lastchangeby varchar(255)   not null
);

CREATE INDEX idx_walletfrom_walletto ON core.wlt_transactions (idwalletfrom, idwalletto);

CREATE TABLE core.prm_permissions
(
    id           int          not null constraint pk_permissions primary key,
    name         varchar(150) not null,
    isblocked    boolean      not null,
    operation    char(1)      not null,
    lastchangeat timestamp    not null,
    lastchangeby varchar(255) not null
);

CREATE TABLE core.prm_profiles
(
    id           bigint       generated by default as identity constraint pk_profile primary key,
    iduser       uuid         not null constraint fk_profile_user references core.ath_users (id),
    idpermission int          not null constraint fk_profile_permission references core.prm_permissions (id),
    operation    char(1)      not null,
    lastchangeat timestamp    not null,
    lastchangeby varchar(255) not null
);

CREATE TABLE core.ath_refreshtokens
(
    id                bigint       generated by default as identity constraint pk_refreshtoken primary key,
    token             varchar(128) not null,
    iduser            uuid         not null constraint fk_refreshtoken_user references core.ath_users (id),
    dateexpired       timestamp    not null,
    revokedat         timestamp    null,
    replacedbytokenid bigint       null,
    operation         char(1)      not null,
    lastchangeat      timestamp    not null,
    lastchangeby      varchar(255) not null
);

CREATE TABLE core.blc_block
(
    id             uuid         not null default gen_random_uuid() constraint pk_block primary key,
    hash           varchar(512) not null,
    merkleroot     varchar(512) not null,
    blocksignature varchar(255) null,
    publickey      varchar(800) not null,
    isvalid        boolean      not null,
    previoushash   varchar(512) not null,
    dateinclusion  timestamp    not null
);

ALTER TABLE core.wlt_transactions
    ADD CONSTRAINT fk_transactions_blocks FOREIGN KEY (idblock) REFERENCES core.blc_block (id);

CREATE TABLE core.btc_status
(
    id          int          not null constraint pk_batchstatus primary key,
    name        varchar(120) not null,
    description varchar(255) not null
);

CREATE TABLE core.btc_validations
(
    id               uuid      not null default gen_random_uuid() constraint pk_batchvalidation primary key,
    beginvalidation  timestamp not null,
    endvalidation    timestamp null,
    idbatchstatus    int       not null constraint fk_batchvalidation_batchstatus references core.btc_status (id),
    blockinvalidated int       not null,
    blockprocessed   int       not null
);

CREATE TABLE core.btc_checkpoints
(
    id      bigint  not null generated by default as identity constraint pk_batchcheckpoint primary key,
    idblock uuid    not null constraint fk_batchcheckpoint_block references core.blc_block (id),
    idbatch uuid    not null constraint fk_batchcheckpoint_batchvalidation references core.btc_validations (id),
    isvalid boolean not null
);

-- TX-1 / SEC-2: Idempotency-Key / nonce anti-replay.
CREATE TABLE core.idm_idempotencykeys
(
    id           uuid         not null constraint pk_idempotencykey primary key,
    requesthash  varchar(128) not null,
    status       int          not null,
    responsebody text         null,
    createdat    timestamp    not null,
    expiresat    timestamp    not null
);
